name             'devops'
maintainer       'Mike Morrow'
maintainer_email 'mmorrow at vt dot edu'
license          'CC-BY-SA'
description      'Installs/Configures devops'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'include_me'
issues_url       'https://github.com/MikeMorrow/devops'
source_url       'https://github.com/MikeMorrow/devops'
supports         'rhel, centos, debian, ubuntu'
